EngineeringKiosk/GermanTechPodcasts

CONTRIBUTING.md

- include impact on society podcasts
- added qudio quality criteria

updated criteria

---

podcasts/neuland.yml

New podcast: Neuland

---

podcasts/mein-scrum-ist-kaputt.yml

New podcast: Mein Scrum ist kaputt!

---

podcasts/devcouch.yml

New podcast: DevCouch

---

podcasts/it-berufe-podcast.yml

New podcast: IT-Berufe Podcast

---

podcasts/Codestammtisch.yml

New podcast: Codestammtisch

---

podcasts/it-ist-alles.yml

New podcast: IT ist alles

---

podcasts/it-at-db.yml

New podcast: IT@DB

---

podcasts/heise-developer-softwarearchitektour.yml

New podcast: heise Developer: SoftwareArchitekTOUR

---

podcasts/bit-rauschen.yml
podcasts/heise-developer-softwarearchitektour.yml

New podcast: Bit-Rauschen

---

podcasts/mac-and-i.yml

New podcast: Mac & I

---

podcasts/kurz-informiert.yml

New podcast: Kurz informiert by heise online

---

podcasts/ct-uplink.yml

New podcast: c't uplink

---

podcasts/auslegungssache.yml

New podcast: Auslegungssache

---

podcasts/binaergewitter.yml

New podcast: Binärgewitter

---

podcasts/freakshow.yml

Fix #12
Pull request #79 needs to be merged BEFORE this one.

New podcast Freakshow

---

podcasts/bits-und-so.yml

New podcast: Bits und so

---

podcasts/apfelfunk.yml

New podcast: Apfelfunk

---

podcasts/chaosradio.yml

New podcast: Chaosradio

---

podcasts/techtiefen.yml

Reactivate podcast: Techtiefen

---

podcasts/requests-for-comments.yml

New podcast: Request for Comments

---

podcasts/code-culture.yml

New podcast: Code Culture

---

podcasts/know-it.yml

New podcast: knowIT

---

podcasts/herzbergs-hoersaal.yml

New podcast: Herzbergs Hörsaal

---

podcasts/computer-und-kommunikation-deutschlandfunk.yml

New podcast: Computer und Kommunikation (Deutschlandfunk)

---

podcasts/autoweird.yml

New podcast: Autoweird

---

podcasts/herzbergs-hoersaal.yml

Related to https://github.com/EngineeringKiosk/GermanTechPodcasts/pull/100
I just fucked up https://github.com/EngineeringKiosk/GermanTechPodcasts/pull/95

Fix "Herzbergs Hörsaal"

---

podcasts/schwarz-code-gold-deutschland-entwicklungsland.yml

Ich hoffe, das passt alles so – bin selbst kein Entwickler und nicht 100prozentig fit in Git. Danke und #KeepUpTheGoodWork!

added Schwarz, Code, Gold

---

podcasts/wp-sofa.yml

New podcast: WP Sofa

---

podcasts/logbuch-digitalien.yml

New podcast: Logbuch Digitalien

---

assets/README.template

Added Frequently Asked Questions section to explain the repository language

---

podcasts/das-duumvirat.yml

Hi,
This is the requested file to nominate the german podcast "Das Duumvirat".

New podcast: Das Duumvirat

---

podcasts/tilpod.yml

Ich habe einmal unseren Podcast TILpod hinzugefügt.
Danke für diesen Service!

TILpod hinzugefügt

---

app/cmd/collectPodcastData.go

If the podcast pipeline cannot download the cover image, the pipeline fails.
This is OK, if we don't have an image at all.
If we have an image (maybe an old one), this is ok enough. In this case, we don't need to fail the pipeline.
Last log message of pipeline run (https://github.com/EngineeringKiosk/GermanTechPodcasts/actions/runs/3083774903/jobs/4985122467):
```
2022/09/19 15:49:19 Processing file ../generated/neuland.json
2022/09/19 15:49:19 Requesting 'Podcasts.GetByFeedID' data from podcast index for feed id 77949
2022/09/19 15:49:19 Downloading https://podcast.hpi.de/images/itunes_image.jpg into ../generated/images/neuland.jpg
404
Error: received non 200 response code
Usage:
GermanTechPodcasts collectPodcastData [flags]
Flags:
--api-key string          API Key for Podcast Index API …
```

Fix a failing pipeline, if the image can't be downloaded

---

podcasts/wo-wir-sind-ist-vorne.yml

Added some tags for #wwsiv

---

podcasts/web-und-design-podcast.yml

New Podcast: "Web & Design Podcast"

---

podcasts/code-and-ship.yml

New Podcast: "Code and Ship"

---

podcasts/index-out-of-bounds.yml

New Podcast: "Index out of bounds"

---

podcasts/game-dev-podcast.yml

New Podcast: "Der GameDev Podcast (Game Dev)"

---

podcasts/focus-on-linux.yml

Hi there,
thanks for the list!
Here are some metrics for this month for our podcast.

[FOCUS ON: Linux] add metrics

---

app/cmd/collectPodcastData.go

This PR should fix things like
> Error: Get "http://media.gamedevpodcast.de/logo_2800.png": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
See the latest Action failure run: https://github.com/EngineeringKiosk/GermanTechPodcasts/actions/runs/3345035908/jobs/5540077014

Fix image download failure

---

podcasts/super-duper-developers-club.yml

Fix #166: Add Super Duper Developers Club Podcast

---

podcasts/bits-und-boeses.yml

New podcast: Add "Bits & Böses - Der Tech Crime Podcast"

---

podcasts/python-podcast.yml

New Podcast: Python Podcast

---

podcasts/mixedcast.yml

New podcast: Mixedcast

---

assets/README.template

Add link to fyyd.de

---

podcasts/isms-x-plain.yml

New podcast: ISMS X-Plain

---

podcasts/python-podcast.yml

Python Podcast: Added weekly_downloads_avg

---

podcasts/herr-zenzes.yml

feat: add 'Herr Zenzes wills wissen' podcast

---

podcasts/einfach-komplex.yml

New Podcast: Einfach komplex

---

podcasts/coding-buddies.yml

New Podcast: Coding Buddies

---

podcasts/focus-on-linux.yml

update FOCUS ON: Linux statistics

---

podcasts/auslegungssache.yml
podcasts/bit-rauschen.yml
podcasts/ct-uplink.yml
podcasts/heise-developer-softwarearchitektour.yml
podcasts/heiseshow.yml
podcasts/ki-update.yml
podcasts/kurz-informiert.yml
podcasts/mac-and-i.yml
podcasts/softwarearchitektour.yml

See https://www.heise.de/Hoeren-Sie-von-uns-unsere-Podcasts-4206659.html

A big update on the heise Podcasts

---

podcasts/techniktechnik.yml

New Podcast: TechnikTechnik

---

podcasts/webcafe.yml

Webcafé is a german tech podcast about webtechnology (esp. react, laravel, typescript and php) and management. This Podcast would fit quite well into the repository.

add new podcast webcafe

---

podcasts/focus-on-linux.yml

This PR updates statistics as the old values were ~2 years old.
Thanks for your great project! 🙂

[FOCUS ON: Linux] update statistics

---

podcasts/devs-on-tape.yml

New Podcast: Devs on Tape

---

podcasts/faxinformatiker.yml

New Podcast: Faxinformatiker

---

podcasts/buzzzoom.yml

New podcast: BuzzZoom
